### ISSUE TITLE
怎么调试代码错误

### ISSUE THREAD

**Issue by Hutao-90** [YWNA/SWBT#2]
开发脚本中的调试过程，怎么捕捉错误，try...catch都捕捉不到错误。
进程失败后，就一直重启，为啥我连错误都捕捉不到了，是我的问题吗？

子进程异常退出时将会自动重启! 能抛出异常原因吗？

**Comment by chenbo29** [comment]
> 开发脚本中的调试过程，怎么捕捉错误，try...catch都捕捉不到错误。
> 进程失败后，就一直重启，为啥我连错误都捕捉不到了，是我的问题吗？
> 
> 子进程异常退出时将会自动重启! 能抛出异常原因吗？

项目本身的设计是在子进程被kill退出时将会重启。请问你的开发平台操作系统是什么？

**Comment by Hutao-90** [comment]
> > 开发脚本中的调试过程，怎么捕捉错误，try...catch都捕捉不到错误。
> > 进程失败后，就一直重启，为啥我连错误都捕捉不到了，是我的问题吗？
> > 子进程异常退出时将会自动重启! 能抛出异常原因吗？
> 
> 项目本身的设计是在子进程被kill退出时将会重启。请问你的开发平台操作系统是什么？

Mac系统，比如，当子进程去执行一个脚本是，该脚本有代码级别的错误，子进程会去重启，但是为什么我在脚本try...catch都不能捕获到异常信息，或者这个项目是否应该在日志文件里把脚本异常的原因抛出来

**Comment by Hutao-90** [comment]
SWBT脚本修改 error_reporting(E_ALL);即可在终端显示运行中脚本异常
